.TH SM 1 "2012 January 23" "SM Framework"

.SH SYNOPSIS
.B sm· 
{options...} os action {action-params}

.SH DESCRIPTION
S{cripting,ystem} Manager (SM) Framework (Core) API array documentation

.SH Installation
To load the os module API, add 'api/os' to the shell/includes file.

.SH Actions
.TP 13
.B arch 
View the architecture of machine
.TP 13
.B arch type
View type of architecture of machine
.TP 13
.B cpu count
Count the numbers of cores of machine
.TP 13
.B is {os}
Test OS system is running
.TP 13
.B open {file}
OS open a file
.TP 13
.B type
View the type of OS that is running
.TP 13
.B version
View OS version
.TP 13
.B version major
View OS major version
.TP 13
.B version minor
View OS minor version
.TP 13
.B version patch
View OS patch version
