.TH SM 1 "2011 November 9" "SM Framework"

.SH SYNOPSIS
.B sm
{options...} json action {action-params}

.SH DESCRIPTION
S{cripting,ystem} Manager (SM) Framework (Core) API json documentation

.SH Installation
To load the json module API, add 'api/json' to the shell/includes file.

.SH Actions
.TP 13
.B get from {path/file.json} {namespace paths}
get namespace paths from given json file and set variables containing the results

